/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package spc.edu;

import javax.swing.JOptionPane;

/**
 *
 * @author SPC
 */
public class LareTicTacToe extends javax.swing.JFrame {

    /**
     * Creates new form LareTicTacToe
     */
    
    
    int turn = 2;
    int buttonused[]={0,0,0,0,0,0,0,0,0};
    int pXwon[]= {0,0,0,0,0,0,0,0,0};
    int pOwon[]= {0,0,0,0,0,0,0,0,0};
    
    int pXwon()
    {
        if(pXwon[0]==1 && pXwon[1]==1 && pXwon[2]==1)
        {
            return 1;
        }
        if(pXwon[3]==1 && pXwon[4]==1 && pXwon[2]==1)
        {
            return 1;
        }
        if(pXwon[6]==1 && pXwon[7]==1 && pXwon[2]==1)
        {
            return 1;
        }
        if(pXwon[0]==1 && pXwon[3]==1 && pXwon[6]==1)
        {
            return 1;
        }
        if(pXwon[1]==1 && pXwon[4]==1 && pXwon[7]==1)
        {
            return 1;
        }
        if(pXwon[2]==1 && pXwon[5]==1 && pXwon[8]==1)
        {
            return 1;
        }
        if(pXwon[0]==1 && pXwon[3]==1 && pXwon[6]==1)
        {
            return 1;
        }
        if(pXwon[1]==1 && pXwon[4]==1 && pXwon[7]==1)
        {
            return 1;
        }
        if(pXwon[2]==1 && pXwon[5]==1 && pXwon[0]==1)
        {
            return 1;
        }
        if(pXwon[2]==1 && pXwon[4]==1 && pXwon[6]==1)
        {
            return 1;
        }
        if(pXwon[0]==1 && pXwon[4]==1 && pXwon[8]==1)
        {
            return 1;
        }
        return 0;
    }
    
    int pOwon()
    {
        if(pOwon[0]==1 && pOwon[1]==1 && pOwon[2]==1)
        {
            return 1;
        }
        if(pOwon[3]==1 && pOwon[4]==1 && pOwon[2]==1)
        {
            return 1;
        }
        if(pOwon[6]==1 && pOwon[7]==1 && pOwon[2]==1)
        {
            return 1;
        }
        if(pOwon[0]==1 && pOwon[3]==1 && pOwon[6]==1)
        {
            return 1;
        }
        if(pOwon[1]==1 && pOwon[4]==1 && pOwon[7]==1)
        {
            return 1;
        }
        if(pOwon[2]==1 && pOwon[5]==1 && pOwon[8]==1)
        {
            return 1;
        }
        if(pOwon[0]==1 && pOwon[3]==1 && pOwon[6]==1)
        {
            return 1;
        }
        if(pOwon[1]==1 && pOwon[4]==1 && pOwon[7]==1)
        {
            return 1;
        }
        if(pOwon[2]==1 && pOwon[5]==1 && pOwon[0]==1)
        {
            return 1;
        }
        if(pOwon[2]==1 && pOwon[4]==1 && pOwon[6]==1)
        {
            return 1;
        }
        if(pOwon[0]==1 && pOwon[4]==1 && pOwon[8]==1)
        {
            return 1;
        }
        return 0;
    }
    public LareTicTacToe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        b2 = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("PLAY!!!");

        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });

        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        reset.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        reset.setForeground(new java.awt.Color(204, 0, 0));
        reset.setText("PLAY AGAN!!!");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(reset)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(355, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(102, 102, 102)
                    .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(372, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        if(buttonused[0]==0)
        {
            if(turn%2==0)
            {
                turn ++;
                b0.setText("X");
                buttonused[0]=1;
                pXwon[0]=1;
                
                int result1=pXwon();
                int result2=pXwon();
                if(result1==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "play X won!!!");
                    
                }
                else if (result2==1)
                {
                     JOptionPane.showMessageDialog(rootPane, "play O won!!!");
                }
            }
            else
            {
                turn ++;
                b0.setText("O");
                buttonused[0]=1;
                  int result1=pXwon();
                int result2=pXwon();
                if(result1==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "play X won!!!");
                    
                }
                else if (result2==1)
                {
                     JOptionPane.showMessageDialog(rootPane, "play O won!!!");
                }       
            }
            }
            else
            {
                    JOptionPane.showMessageDialog(rootPane,"This button is usser!!!");
            }
    }//GEN-LAST:event_b0ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        if(buttonused[1]==0)
        {
            if(turn%2==0)
            {
                turn ++;
                b1.setText("X");
                buttonused[1]=1;
                pXwon[1]=1;
                
                int result1=pXwon();
                int result2=pXwon();
                if(result1==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "play X won!!!");
                    
                }
                else if (result2==1)
                {
                     JOptionPane.showMessageDialog(rootPane, "play O won!!!");
                }
            }
            else
            {
                turn ++;
                b1.setText("O");
                buttonused[1]=1;
                  int result1=pXwon();
                int result2=pXwon();
                if(result1==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "play X won!!!");
                    
                }
                else if (result2==1)
                {
                     JOptionPane.showMessageDialog(rootPane, "play O won!!!");
                }       
            }
            }
            else
            {
                    JOptionPane.showMessageDialog(rootPane,"This button is usser!!!");
            }
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        if(buttonused[2]==0)
        {
            if(turn%2==0)
            {
                turn ++;
                b2.setText("X");
                buttonused[2]=1;
                pXwon[2]=1;

                int result1=pXwon();
                int result2=pXwon();
                if(result1==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "play X won!!!");
                    
                }
                else if (result2==1)
                {
                     JOptionPane.showMessageDialog(rootPane, "play O won!!!");
                }
            }
            else
            {
                turn ++;
                b2.setText("O");
                buttonused[2]=1;
                  int result1=pXwon();
                int result2=pXwon();
                if(result1==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "play X won!!!");
                    
                }
                else if (result2==1)
                {
                     JOptionPane.showMessageDialog(rootPane, "play O won!!!");
                }       
            }
            }
            else
            {
                    JOptionPane.showMessageDialog(rootPane,"This button is usser!!!");
            }
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        if(buttonused[3]==0)
        {
            if(turn%2==0)
            {
                turn ++;
                b3.setText("X");
                buttonused[3]=1;
                pXwon[3]=1;
                
                int result1=pXwon();
                int result2=pXwon();
                if(result1==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "play X won!!!");
                    
                }
                else if (result2==1)
                {
                     JOptionPane.showMessageDialog(rootPane, "play O won!!!");
                }
            }
            else
            {
                turn ++;
                b3.setText("O");
                buttonused[3]=1;
                  int result1=pXwon();
                int result2=pXwon();
                if(result1==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "play X won!!!");
                    
                }
                else if (result2==1)
                {
                     JOptionPane.showMessageDialog(rootPane, "play O won!!!");
                }       
            }
            }
            else
            {
                    JOptionPane.showMessageDialog(rootPane,"This button is usser!!!");
            }
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
       if(buttonused[4]==0)
        {
            if(turn%2==0)
            {
                turn ++;
                b4.setText("X");
                buttonused[4]=1;
                pXwon[4]=1;
                
                int result1=pXwon();
                int result2=pXwon();
                if(result1==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "play X won!!!");
                    
                }
                else if (result2==1)
                {
                     JOptionPane.showMessageDialog(rootPane, "play O won!!!");
                }
            }
            else
            {
                turn ++;
                b4.setText("O");
                buttonused[4]=1;
                  int result1=pXwon();
                int result2=pXwon();
                if(result1==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "play X won!!!");
                    
                }
                else if (result2==1)
                {
                     JOptionPane.showMessageDialog(rootPane, "play O won!!!");
                }       
            }
            }
            else
            {
                    JOptionPane.showMessageDialog(rootPane,"This button is usser!!!");
            }
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        if(buttonused[5]==0)
        {
            if(turn%2==0)
            {
                turn ++;
                b0.setText("X");
                buttonused[5]=1;
                pXwon[5]=1;
                
                int result1=pXwon();
                int result2=pXwon();
                if(result1==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "play X won!!!");
                    
                }
                else if (result2==1)
                {
                     JOptionPane.showMessageDialog(rootPane, "play O won!!!");
                }
            }
            else
            {
                turn ++;
                b5.setText("O");
                buttonused[5]=1;
                  int result1=pXwon();
                int result2=pXwon();
                if(result1==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "play X won!!!");
                    
                }
                else if (result2==1)
                {
                     JOptionPane.showMessageDialog(rootPane, "play O won!!!");
                }       
            }
            }
            else
            {
                    JOptionPane.showMessageDialog(rootPane,"This button is usser!!!");
            }
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
       if(buttonused[6]==0)
        {
            if(turn%2==0)
            {
                turn ++;
                b6.setText("X");
                buttonused[6]=1;
                pXwon[6]=1;
                
                int result1=pXwon();
                int result2=pXwon();
                if(result1==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "play X won!!!");
                    
                }
                else if (result2==1)
                {
                     JOptionPane.showMessageDialog(rootPane, "play O won!!!");
                }
            }
            else
            {
                turn ++;
                b6.setText("O");
                buttonused[6]=1;
                  int result1=pXwon();
                int result2=pXwon();
                if(result1==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "play X won!!!");
                    
                }
                else if (result2==1)
                {
                     JOptionPane.showMessageDialog(rootPane, "play O won!!!");
                }       
            }
            }
            else
            {
                    JOptionPane.showMessageDialog(rootPane,"This button is usser!!!");
            }
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        if(buttonused[7]==0)
        {
            if(turn%2==0)
            {
                turn ++;
                b7.setText("X");
                buttonused[7]=1;
                pXwon[7]=1;
                
                int result1=pXwon();
                int result2=pXwon();
                if(result1==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "play X won!!!");
                    
                }
                else if (result2==1)
                {
                     JOptionPane.showMessageDialog(rootPane, "play O won!!!");
                }
            }
            else
            {
                turn ++;
                b7.setText("O");
                buttonused[7]=1;
                  int result1=pXwon();
                int result2=pXwon();
                if(result1==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "play X won!!!");
                    
                }
                else if (result2==1)
                {
                     JOptionPane.showMessageDialog(rootPane, "play O won!!!");
                }       
            }
            }
            else
            {
                    JOptionPane.showMessageDialog(rootPane,"This button is usser!!!");
            }
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        if(buttonused[8]==0)
        {
            if(turn%2==0)
            {
                turn ++;
                b8.setText("X");
                buttonused[8]=1;
                pXwon[8]=1;
                
                int result1=pXwon();
                int result2=pXwon();
                if(result1==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "play X won!!!");
                    
                }
                else if (result2==1)
                {
                     JOptionPane.showMessageDialog(rootPane, "play O won!!!");
                }
            }
            else
            {
                turn ++;
                b8.setText("O");
                buttonused[8]=1;
                  int result1=pXwon();
                int result2=pXwon();
                if(result1==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "play X won!!!");
                    
                }
                else if (result2==1)
                {
                     JOptionPane.showMessageDialog(rootPane, "play O won!!!");
                }       
            }
            }
            else
            {
                    JOptionPane.showMessageDialog(rootPane,"This button is usser!!!");
            }
    }//GEN-LAST:event_b8ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        b0.setText("");
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        turn=2;
        for(int i=0;i<9;i++)
        {
            buttonused[i]=0;
        }
        for(int i=0;i<9;i++)
        {
            pXwon[i]=0;
        }
        for(int i=0;i<9;i++)
        {
            pOwon
                    [i]=0;
        }
    }//GEN-LAST:event_resetActionPerformed
 
/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LareTicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LareTicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LareTicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LareTicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LareTicTacToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables
}
